# Generated by Django 5.1 on 2024-09-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="category",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="target_muscles",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
        migrations.DeleteModel(
            name="MuscleGroup",
        ),
    ]
