# Generated by Django 5.1 on 2024-09-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberprofile",
            name="date_of_birth",
        ),
    ]
